### PR TITLE
Initial webpage commit

### PR DESCRIPTION
**Pull request by khrijunk2**
Initial webpage commit

### CODE REVIEW

**Review by Heathtech — APPROVED** [review]
tl;dr lgtm

**Comment by mccartney-joseph** [comment]
This is trash. Nice image though

**Comment by khrijunk2** [comment]
> This is trash. Nice image though

that's fair

**Comment by mccartney-joseph** [comment]
(┛ಠ_ಠ)┛彡┻━┻ 


go for it

**Pull request merged**
